#!/bin/bash
yum install nfs-utils
mkdir /nfsshare
chmod 777 /nfsshare
echo "/nfsshare *(rw,syn)" > /etc/exports
echo "-A INPUT -m state --state NEW -m tcp -p tcp --dport 2049 -j ACCEPT" >>/etc/sysconfig/iptables
echo "-A INPUT -m state --state NEW -m tcp -p tcp --dport 111 -j ACCEPT" >>/etc/sysconfig/iptables
echo "-A INPUT -m state --state NEW -m udp -p udp --dport 111 -j ACCEPT" >>/etc/sysconfig/iptables
service nfs start
chkconfig nfs on
echo "done"
